sudo apt-get install docker.io

name : Workflow
on:
Workflow_run:
  push:
    branches: [ "main"]
jobs:
 steps:
  - uses: actions/checkout@v4
  - name: Use Node.js
    uses: actions/setup-node@v4
    with:
    node-version: '20.x'
    name: nps install, run, test
    run: npm install
         npm run lint
         npm test


   - name: Docker
     run:
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }}/directors-dev .
          docker push ${{ secrets.DOCKER_REPO }}/directors-dev
      with:
        push: true
        tags: ghcr.io/&{{github.repository}}"latest

 slackNotify:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: fail_test
    steps:
      - name: Notify message to slack
        uses: rtCamp/action-slack-notify@v2
        env:
           EMAIL: &{{secrets.MALE_USERNAME}}
           PASSWORD: &{{secrets.MAIL_PASSWORD}}
        
