server {
    listen 8800;
    access_log /var/log/nginx/referer_access.log main;
    error_log /var/log/nginx/referer_error.log;
    valid_referers none server_names
            *.example.com;
    if ($invalid_referer) {
        return 403;
    }

    location / {
        root /usr/share/nginx/html;
    }

}
   log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
